[build]
builder = "nixpacks"

[deploy]
startCommand = "python init_db.py && gunicorn app:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
healthcheckPath = "/health"
healthcheckTimeout = 10

[nixpacks]
features = ["python"]

[nixpacks.setup]
installCommand = "pip install --no-cache-dir -r requirements.txt" 