[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/health"
healthcheckTimeout = 100

[nixpacks]
features = ["python"]

[nixpacks.setup]
installCommand = "pip install --no-cache-dir -r requirements.txt" 